[package]
name = "ur-rs"
version = "0.1.0"
authors = ["Dominik Spicher <dominikspicher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
cbor = "0.4.1"
crc = "1.8.1"
hex = "0.4.2"
phf = { version = "0.8.0", features = ["macros"] }
rand_xoshiro = "0.4.0"
rust-crypto = "0.2.36"
thiserror = "1.0.20"

[dev-dependencies]

